image: $DOCKER_REGISTRY_PREFIX/2smart/utils/combined-ci-image:buildx

stages:
  - test
  - build
  - release
  - buildx

before_script:
  - git clone https://oauth2:$ACCESS_TOKEN@$DOCKER_UTILS_REPO_URL
  - mv docker-utils/utils.sh docker.sh

services:
  - name: $DOCKER_REGISTRY_PREFIX/2smart/base-images/docker-dind
    alias: docker
    command: [ "--experimental" ]
  - name: $DOCKER_REGISTRY_PREFIX/2smart/standalone/services/emqx:release
    alias: emqx-emqx

variables:
  EMQX_NAME: emqx_broker
  EMQX_LISTENER__TCP__EXTERNAL: 1883
  EMQX_LISTENER__WS__EXTERNAL: 8083
  EMQX_ACL_NOMATCH: allow
  EMQX_ACL_FILE: etc/empty.conf
  MODE: 'test'
  MQTT_URI: 'mqtt://emqx-emqx:1883'
  TEST_TIMEOUT: 15000
  TEST_SERVER_PORT: 8000
  DEVICE_NAME: 'Tesla Bridge'
  CLIENT_ID: '81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384'
  CLIENT_SECRET: 'c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3'
  OAUTH_ACCESS_TOKEN: 'qts-e459af079760dc51beb975a2431d23f920057db8fd946047fbd6a2c409fc5fb9'
  OAUTH_REFRESH_TOKEN: 'd68b168f69a7cc4f7b9af8b7150d86a556a221a2b7167c056dbb21171930c256'
  IMAGE_PLATFORMS: linux/amd64,linux/arm/v7

lint:
  before_script:
    - npm i
  stage: test
  script:
    - npm run test:lint
  only:
    - 'merge_requests'
    - 'master'

test:
  before_script:
    - apk add --update netcat-openbsd
    - npm i
  stage: test
  script:
    - npm run test
  only:
    - 'merge_requests'
    - 'master'

build:
  stage: build
  script:
    - ./docker.sh rundaemon
    - ./docker.sh build
    - ./docker.sh push
  only:
    - 'master'

release:
  stage: release
  script:
    - ./docker.sh rundaemon
    - ./docker.sh release_bridge_type
  only:
    - 'release'

buildx:
  stage: buildx
  script:
    - ./docker.sh rundaemon
    - ./docker.sh login
    - SOURCE_TAG=$MULTIPLATFORM_TAG ./docker.sh buildx
  when: manual
  allow_failure: true
